DROP TABLE IF EXISTS `allergies`;
DROP TABLE IF EXISTS `prescription_diagnosis`;
DROP TABLE IF EXISTS `prescriptions`;
DROP TABLE IF EXISTS `abbreviations`;
DROP TABLE IF EXISTS `dosage`;
DROP TABLE IF EXISTS `synonyms`;
DROP TABLE IF EXISTS `dosage`;
DROP TABLE IF EXISTS `antibiotics`;
DROP TABLE IF EXISTS `antibiotic_groups`;
