# Generated by Django 5.1.4 on 2025-01-28 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_abbreviations_abusage_allergies_antibioticgroups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='birth_country_code',
            field=models.ForeignKey(db_column='birth_country_code', on_delete=django.db.models.deletion.PROTECT, related_name='birth_country', to='backend.countries'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dial_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dial_code', to='backend.dialcodes'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='resident_country_code',
            field=models.ForeignKey(db_column='resident_country_code', on_delete=django.db.models.deletion.PROTECT, related_name='resident_country', to='backend.countries'),
        ),
    ]
