name: TEST
on:
    push:
        branches: [ "main" ]

jobs:
    Test:
        runs-on: ubuntu-latest
        env: 
            secret: ${{secrets.ENV_FILE}},
        steps:
            - uses: actions/checkout@v4
            - name: Test database
              run: pipx install virtualenv
                   python3 -m venv venv
                   source venv/bin/activate
                   python3 -m pip install -r requirements.txt
                   echo "${{ env.DB_USER }}" > database/.env